# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-15-intel, ubuntu-latest]
        java: [8, 11]
        exclude:
          - os: windows-latest
            java: 8
          - os: macos-15-intel
            java: 8

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: "zulu"
        java-version: "${{ matrix.java }}"
        cache: "sbt"
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt "travisQuickListReflectionTest" "filesJVM/jacoco" "allTests"
      env:
        SBT_OPTS: -Xmx2g -Dswoval.format=false -Dfile.encoding=UTF8 -Dswoval.skip.native=true -Dswoval.fork.tests=true -Dswoval.alltests.iterations=50
